name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets.
version: 1.0.0-pre.1
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=2.8.0 <3.0.0'
  flutter: '>=1.7.4'

dependencies:
  # Plugin for parsing html
  html:
    # path: ../html
    git:
      url: https://github.com/jlandon/html
      ref: master

  # Plugins for parsing css
  csslib: ^0.16.1
  css_colors: ^1.0.2

  # Plugins for rendering the <video> tag.
  video_player: ^0.10.2+1
  chewie: ^0.9.8

  # Plugin for rendering the <iframe> tag.
  webview_flutter: ^0.3.14+1

  # Plugins for rendering the <audio> tag.
  chewie_audio: ^1.0.0+1

  # Plugins for rendering the <svg> tag.
  flutter_svg: ^0.18.0

  flutter:
    sdk: flutter

dependency_overrides:
  csslib:
    git:
      url: https://github.com/jfri/csslib.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

